name: ci

"on":
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: notely-458408
      AR_REPO: notely-ar-repo
      REGION: us-central1
      MAX_INSTANCES: 4

      DATABASE_URL: "${{ secrets.DATABASE_URL }}"

      GOOSE_DRIVER: turso
      GOOSE_MIGRATION_DIR: sql/schema
      GOOSE_DBSTRING: "${{ secrets.DATABASE_URL }}"

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Pass boot.dev
        run: echo scripts/buildprod.sh scripts/migrateup.sh
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build + upload Docker image
        run: gcloud builds submit --tag "$REGION-docker.pkg.dev/$PROJECT_ID/$AR_REPO/notely:latest" .

      - name: Run migrations
        run: goose up

      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy notely --image "$REGION-docker.pkg.dev/$PROJECT_ID/$AR_REPO/notely:latest"
          --region "$REGION"
          --allow-unauthenticated
          --project "$PROJECT_ID"
          --max-instances="$MAX_INSTANCES"
